import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const symbols = [
  "NSE:NIFTY", "NSE:BANKNIFTY", "NSE:FINNIFTY",
  "NSE:RELIANCE", "NSE:HDFCBANK", "NSE:ICICIBANK", "NSE:INFY", "NSE:TCS",
  "NSE:ITC", "NSE:SBIN", "NSE:BHARTIARTL", "NSE:LT", "NSE:BAJFINANCE",
  "NSE:AXISBANK", "NSE:KOTAKBANK", "NSE:HINDUNILVR", "NSE:TATASTEEL", "NSE:TATAMOTORS",
  "NSE:M&M", "NSE:MARUTI", "NSE:SUNPHARMA", "NSE:JSWSTEEL", "NSE:POWERGRID",
  "NSE:NTPC", "NSE:COALINDIA", "NSE:BPCL", "NSE:IOC", "NSE:ONGC",
  "NSE:ADANIENT", "NSE:ADANIPORTS", "NSE:APOLLOHOSP", "NSE:ASIANPAINT", "NSE:BRITANNIA",
  "NSE:CIPLA", "NSE:DIVISLAB", "NSE:DRREDDY", "NSE:EICHERMOT", "NSE:GRASIM",
  "NSE:HINDALCO", "NSE:HEROMOTOCO", "NSE:INDUSINDBK", "NSE:LTIM", "NSE:NESTLEIND",
  "NSE:SBILIFE", "NSE:SHRIRAMFIN", "NSE:TATACONSUM", "NSE:TECHM", "NSE:TITAN",
  "NSE:ULTRACEMCO", "NSE:WIPRO", "NSE:DLF", "NSE:HAL", "NSE:BEL",
  "NSE:OBEROIRLTY", "NSE:PFC", "NSE:RECLTD", "NSE:TRENT", "NSE:HINDZINC",
  "NSE:GMRINFRA", "NSE:ASHOKLEY", "NSE:TATACOMM", "NSE:TATAPOWER", "NSE:FEDERALBNK",
  "NSE:IDFCFIRSTB", "NSE:PNB", "NSE:CANBK", "NSE:BANKBARODA", "NSE:SAIL",
  "NSE:JINDALSTEL", "NSE:NMDC", "NSE:NATIONALUM", "NSE:AMBUJACEM", "NSE:ACC",
  "NSE:CONCOR", "NSE:LICHSGFIN", "NSE:IGL", "NSE:MGL", "NSE:PETRONET",
  "NSE:HINDPETRO", "NSE:GAIL", "NSE:BHEL", "NSE:VOLTAS", "NSE:HAVELLS",
  "NSE:POLYCAB", "NSE:DIXON", "NSE:MUTHOOTFIN", "NSE:CHOLAFIN", "NSE:SRF",
  "NSE:UPL", "NSE:LTF", "NSE:ABFRL", "NSE:PAGEIND", "NSE:TVSMOTOR",
  "NSE:BALKRISIND", "NSE:AUBANK", "NSE:BANDHANBNK", "NSE:ESCORTS", "NSE:PIDILITIND"
];

const file = path.join(__dirname, 'data/scan_symbols.json');
fs.writeFileSync(file, JSON.stringify(symbols, null, 2), 'utf8');
console.log('Successfully wrote 98 liquid F&O symbols to scan_symbols.json!');
